name: Main CI

on:
  push:
    branches: main
    paths:
      - ".github/workflows/main_ci.yml"
      - "cmake/**"
      - "include/**"
      - "src/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - "vcpkg.json"
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - ".github/workflows/main_ci.yml"
      - "cmake/**"
      - "include/**"
      - "src/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - "vcpkg.json"
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build-type:
          - debug
          - release
        runtime:
          - all
          - flatrim
          - vr
        compiler:
          - msvc
          - clang-cl

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ng

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          configurePreset: build-${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
          buildPreset: ${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg-${{ matrix.runtime }}
