name: Main CI

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths:
      - ".github/workflows/main_ci.yml"
      - "cmake/**"
      - "include/**"
      - "src/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - "vcpkg.json"
  workflow_dispatch:

concurrency:
  group: main-ci
  cancel-in-progress: true

env:
  VCPKG_COMMIT_ID: e85eecfb39341bd8a76952b33b606a083cdeab1c

jobs:
  test-build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build:
          - debug
          - release
        runtime:
          - all
          - flatrim

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: build-${{ matrix.build }}-${{ matrix.runtime }}
          buildPreset: ${{ matrix.build }}-${{ matrix.runtime }}
