name: Maintenance

on:
  push:
    branches: main
    paths:
      - "include/**"
      - "src/**"
  workflow_dispatch:

concurrency:
  group: maintenance
  cancel-in-progress: true

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run clang-format
        uses: jayllyz/clang-format-action@v1

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "ci: maintenance"
